### ISSUE TITLE
Recommending paper

### ISSUE THREAD

**Issue by MonsterZhZh** [xialeiliu/Awesome-Incremental-Learning#10]
Hi! I find this interesting paper named "Incremental Learning of Object Detectors without Catastrophic Forgetting" (ICCV2017) focusing on object detection.
[Paper](http://openaccess.thecvf.com/content_iccv_2017/html/Shmelkov_Incremental_Learning_of_ICCV_2017_paper.html)
[Code](http://openaccess.thecvf.com/content_iccv_2017/html/Shmelkov_Incremental_Learning_of_ICCV_2017_paper.html)

**Comment by xialeiliu** [comment]
Thanks!
