### ISSUE TITLE
Considering recommender system paper

### ISSUE THREAD

**Issue by russellkim** [xialeiliu/Awesome-Incremental-Learning#100]
Hi Xialei,

Thanks so much for contributing such a great repository! 
Could you consider adding the paper "A Survey on Incremental Update for Neural Recommender Systems"? 

In practical recommender systems, incremental updating is a very important subject. For researchers who are studying RecSys it will be helpful. 

Paper: https://arxiv.org/abs/2303.02851

Thanks for your consideration!

**Comment by xialeiliu** [comment]
Sure.
