### ISSUE TITLE
Considering our NeurIPS 22 and CVPR 23 class incremental learning series

### ISSUE THREAD

**Issue by ZHUANGHP** [xialeiliu/Awesome-Incremental-Learning#109]
NeurIPS 22: [ACIL: Analytic Class-Incremental Learning with Absolute Memorization and Privacy Protection](https://proceedings.neurips.cc/paper_files/paper/2022/hash/4b74a42fc81fc7ee252f6bcb6e26c8be-Abstract-Conference.html)

and 

CVPR 23 [GKEAL: Gaussian Kernel Embedded Analytic Learning for Few-Shot Class Incremental Task](http://openaccess.thecvf.com/content/CVPR2023/html/Zhuang_GKEAL_Gaussian_Kernel_Embedded_Analytic_Learning_for_Few-Shot_Class_Incremental_CVPR_2023_paper.html)

Thanks!

**Comment by xialeiliu** [comment]
Thanks for the suggestion.
