### ISSUE TITLE
Add ICCV 2023 Paper 

### ISSUE THREAD

**Issue by ShiWuxuan** [xialeiliu/Awesome-Incremental-Learning#126]
Thanks for contributing such a great repository!

Would you please add the following paper published at ICCV 2023?

Paper title: Prototype Reminiscence and Augmented Asymmetric Knowledge Aggregation for Non-Exemplar Class-Incremental Learning
Paper link: https://openaccess.thecvf.com/content/ICCV2023/html/Shi_Prototype_Reminiscence_and_Augmented_Asymmetric_Knowledge_Aggregation_for_Non-Exemplar_Class-Incremental_ICCV_2023_paper.html
Code link: https://github.com/ShiWuxuan/PRAKA
keywords: Prototype, Class Incremental learning

Thanks for your consideration!

**Comment by xialeiliu** [comment]
Sure, thanks.
