### ISSUE TITLE
Request to add published long survey article and two other published works 

### ISSUE THREAD

**Issue by MrtnMndt** [xialeiliu/Awesome-Incremental-Learning#133]
Dear Xialei,
thank you for maintaining this great list!

We have authored several published (full) continual/lifelong learning papers and I am wondering if you could please add them to the list. One of them might be of particular interest to the community, as it is a broad recent published survey paper from 2023: 

 1. Survey paper: "A wholistic view of continual learning with deep neural networks: Forgotten lessons and the bridge to active and open world learning"
Published in: Neural Networks 160, 2023 
Link: https://www.sciencedirect.com/science/article/pii/S089360802300014X (or on arXiv) 

2. "A Procedural World Generation Framework for Systematic Evaluation of Continual Learning"
Published in: NeurIPS 2021 
Link: https://datasets-benchmarks-proceedings.neurips.cc/paper/2021/hash/d645920e395fedad7bbbed0eca3fe2e0-Abstract-round1.html (or on arXiv) 
Code: https://github.com/ccc-frankfurt/EndlessCL-Simulator-Source 

3. "Unified Probabilistic Deep Continual Learning through Generative Replay and Open Set Recognition" 
Published in: Journal of Imaging 8:4, 2022
Link: https://www.mdpi.com/2313-433X/8/4/93 (or on arXiv) 
Code: https://github.com/MrtnMndt/OpenVAE_ContinualLearning

**Comment by xialeiliu** [comment]
Hey Martin, thanks for providing these awesome papers. done!
