### ISSUE TITLE
Added code for NeurIPS 2023 paper. 

### ISSUE THREAD

**Issue by haizhou-shi** [xialeiliu/Awesome-Incremental-Learning#134]
Hi, thank you for maintaining such a great repo! 

We have released our code of the NeurIPS 2023 paper "A Unified Approach to Domain Incremental Learning with Memory: Theory and Algorithm" at https://github.com/Wang-ML-Lab/unified-continual-learning. 

Could you please kindly update the readme?  Thank you so much in advance!

**Comment by xialeiliu** [comment]
Sure, thanks.
