### ISSUE TITLE
Add AAAI 2024 Paper

### ISSUE THREAD

**Issue by kthone** [xialeiliu/Awesome-Incremental-Learning#137]
Thank you for the great work! I have gotten so much help from this repository while conducting research on continual learning. 

I kindly suggest you to add AAAI2024 paper on Class-Incremental Learning: Cross-Class Feature Augmentation for Class Incremental Learning (Link: https://arxiv.org/abs/2304.01899)

Thank you for consideration!

**Comment by xialeiliu** [comment]
Sure.
