### ISSUE TITLE
Add ICCV 2023 paper 

### ISSUE THREAD

**Issue by Jin0316** [xialeiliu/Awesome-Incremental-Learning#141]
Thank you for contributing to such a great repository for continual learning literature.

Could you please add the following paper that was published in ICCV 2023?

Paper: Growing a Brain with Sparsity-Inducing Generation for Continual Learning

Url: https://openaccess.thecvf.com/content/ICCV2023/papers/Jin_Growing_a_Brain_with_Sparsity-Inducing_Generation_for_Continual_Learning_ICCV_2023_paper.pdf

Code: https://github.com/Jin0316/GrowBrain

Thanks for your consideration !

**Comment by xialeiliu** [comment]
Sure, thanks for the information.
