### ISSUE TITLE
Please add 'MIND: Multi-Task Incremental Network Distillation' accepted at AAAI 2024

### ISSUE THREAD

**Issue by jbonato1** [xialeiliu/Awesome-Incremental-Learning#142]
Thanks for contributing such a great repository!

Would you please add the following paper published at AAAI 2024?

Paper title: MIND: Multi-Task Incremental Network Distillation
Paper link: https://arxiv.org/abs/2312.02916
Code link: https://github.com/Lsabetta/MIND
keywords: Replay-free Class Incremental learning

Thanks for your consideration!

**Comment by xialeiliu** [comment]
Sure
