### ISSUE TITLE
Add code to ICCV 2023 paper and Add CVPR 2024 paper

### ISSUE THREAD

**Issue by ranarag** [xialeiliu/Awesome-Incremental-Learning#155]
Thank you for contributing to such a great repository for continual learning literature.

Could you please add code to the following paper that was published in ICCV 2023?

Paper: Exemplar-Free Continual Transformer with Convolutions

Code: https://github.com/CVIR/contracon

Also, could you please add the following paper and code that has been accepted in CVPR 2024?

Paper: https://arxiv.org/pdf/2403.20317

Code: https://github.com/CVIR/ConvPrompt

Thanks for your consideration !

**Comment by xialeiliu** [comment]
Sure, thanks for your information.
