### ISSUE TITLE
consider adding  AAAI2024 paper

### ISSUE THREAD

**Issue by tobocca** [xialeiliu/Awesome-Incremental-Learning#171]
Hi Xialei Liu,

Thank you for maintaining such a great repo for continual learning literature!

Could you please add the following paper that was published in AAAI2024

Paper: Learning Task-Aware Language-Image Representation for Class-Incremental Object Detection

Url: https://ojs.aaai.org/index.php/AAAI/article/view/28537/29047

Thanks for your consideration!

**Comment by xialeiliu** [comment]
Sure
