### ISSUE TITLE
consider adding JBCS survey article

### ISSUE THREAD

**Issue by evertonaleixo** [xialeiliu/Awesome-Incremental-Learning#174]
Hi Xialei Liu,

Thank you for maintaining such a great repo for continual learning literature!

Could you please add the following paper that was published in JBCS? I will also add a [PR](https://github.com/xialeiliu/Awesome-Incremental-Learning/pull/173).

Paper: Catastrophic Forgetting in Deep Learning: A Comprehensive Taxonomy

Url: https://journals-sol.sbc.org.br/index.php/jbcs/article/view/3966
DOI: https://doi.org/10.5753/jbcs.2024.3966

Thanks for your consideration!

**Comment by xialeiliu** [comment]
Sure
