### ISSUE TITLE
Paper Suggestion

### ISSUE THREAD

**Issue by tyler-hayes** [xialeiliu/Awesome-Incremental-Learning#18]
Hi, I would like to suggest adding our lab's paper "REMIND Your Neural Network to Prevent Catastrophic Forgetting"

It is accepted to ECCV-2020 and performs incremental classification on the ImageNet and CORe50 datasets, as well as incremental visual question answering on the TDIUC and CLEVR datasets.

arXiv: [https://arxiv.org/abs/1910.02509](https://arxiv.org/abs/1910.02509)
ecva: [https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123530460.pdf](https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123530460.pdf)
code: [https://github.com/tyler-hayes/REMIND](https://github.com/tyler-hayes/REMIND)

**Comment by xialeiliu** [comment]
Thanks. Updated.
