### ISSUE TITLE
paper recommendation

### ISSUE THREAD

**Issue by maggie0106** [xialeiliu/Awesome-Incremental-Learning#19]
Hi Xialei,

Thanks for gathering all the papers. It is quite helpful.

Could you add our recent paper "GraphSAIL: Graph Structure Aware Incremental Learning for Recommender Systems" which has been recently accepted by CIKM 2020: https://arxiv.org/abs/2008.13517.

Thank you,
Yingxue

**Comment by xialeiliu** [comment]
Sure. Thanks.
