### ISSUE TITLE
Contributing to ContinualAI wiki!

### ISSUE THREAD

**Issue by vlomonaco** [xialeiliu/Awesome-Incremental-Learning#2]
Hi @xialeiliu, nice list you have here! :100: :smile: 

At http://continualai.org we have an ongoing project for an open-source collaborative **Wiki** on Incremental/Continual Learning: https://github.com/ContinualAI/wiki

It would be great to have you in the community and join forces on this common endeavor!

Best,
Vincenzo

**Comment by xialeiliu** [comment]
Hi Vincenzo,
Thanks! I am glad to have the chance contributing to the continual learning community.
BTW, Awesome work and nice website, I will put it on my github page as well.

Best regards,
Xialei
