### ISSUE TITLE
Task-incremental Learning/Class-incremental Learning

### ISSUE THREAD

**Issue by Qjizhi** [xialeiliu/Awesome-Incremental-Learning#25]
It seems most of the papers are doing research on Class-incremental Learning, is there any good paper focusing on Task-incremental Learning? For example, from object detection model increases a new feature let's say segmentation.

**Comment by xialeiliu** [comment]
Task-incremental learning often refers to classification tasks, such as learning from Birds -> Flowers -> Cars, which is quite popular from the very beginning, there are several papers in this rep working on this setting.

Also I worked on Task-incremental learning on object detection: feel free to check this [paper](https://arxiv.org/abs/2002.05347), but this is rarely explored.

What you propose is quite interesting if I understood correctly. One example could be learning from depth estimation -> segmentation -> Surface Normal in NYU-v2 dataset. This could be also tested on much larger multi-task dataset, such as [Taskonomy: Disentangling Task Transfer Learning].  However, I haven't noticed work on this setting.

**Comment by Qjizhi** [comment]
> Task-incremental learning often refers to classification tasks, such as learning from Birds -> Flowers -> Cars, which is quite popular from the very beginning, there are several papers in this rep working on this setting.
> 
> Also I worked on Task-incremental learning on object detection: feel free to check this [paper](https://arxiv.org/abs/2002.05347), but this is rarely explored.
> 
> What you propose is quite interesting if I understood correctly. One example could be learning from depth estimation -> segmentation -> Surface Normal in NYU-v2 dataset. This could be also tested on much larger multi-task dataset, such as [Taskonomy: Disentangling Task Transfer Learning]. However, I haven't noticed work on this setting.

Hi xiale,
Thanks for your reply,
