### ISSUE TITLE
Paper Suggestion

### ISSUE THREAD

**Issue by cuijiahui** [xialeiliu/Awesome-Incremental-Learning#28]
Hi Xialei Liu,

Thanks for gathering all the papers. It is quite helpful.

I find this interesting paper named "Complementary Learning for Overcoming Catastrophic Forgetting Using Experience Replay" focusing on continual learning.

Arxiv Link: https://arxiv.org/abs/1903.04566

Best,
Jiahui Cui

**Comment by xialeiliu** [comment]
Thanks.

**Comment by cuijiahui** [comment]
Hi Xialei Liu,

Thanks for gathering all the papers. It is quite helpful.
Is there the code of the paper named  "Complementary Learning for Overcoming Catastrophic Forgetting Using Experience Replay"?

Best,
Jiahui Cui
