### ISSUE TITLE
Can you please add the following WACV 2021 paper in repo

### ISSUE THREAD

**Issue by vinodkkurmi** [xialeiliu/Awesome-Incremental-Learning#36]
Hi @xialeiliu , please add the following paper in repo.

Paper: https://openaccess.thecvf.com/content/WACV2021/html/Kurmi_Do_Not_Forget_to_Attend_to_Uncertainty_While_Mitigating_Catastrophic_WACV_2021_paper.html
Project:  https://delta-lab-iitk.github.io/Incremental-learning-AU/

Thanks

**Comment by xialeiliu** [comment]
Sure. Thanks.
