### ISSUE TITLE
Is there a streaming incremental learning paper？

### ISSUE THREAD

**Issue by KangTomwk** [xialeiliu/Awesome-Incremental-Learning#37]
I want to find some papers related to streaming incremental learning

**Comment by xialeiliu** [comment]
You can check this one, see if you can find more useful references there.
https://arxiv.org/abs/2009.00919

**Comment by KangTomwk** [comment]
> You can check this one, see if you can find more useful references there.
> https://arxiv.org/abs/2009.00919
hi, is this only one?？

**Comment by xialeiliu** [comment]
I mean you can find more in this paper at the experimental section of competing methods.

**Comment by KangTomwk** [comment]
> I mean you can find more in this paper at the experimental section of competing methods.

I don't understand what you mean too much！！！
