### ISSUE TITLE
Add ICML 2021 paper 

### ISSUE THREAD

**Issue by akileshbadrinaaraayanan** [xialeiliu/Awesome-Incremental-Learning#40]
Hi @xialeiliu ,

Thanks for maintaining this repo. Can I request you to add our recent paper published at ICML 2021 (also at ICLR NERL workshop https://sites.google.com/view/neverendingrl as a spotlight) in the repo?

Paper: 
Continuous Coordination As a Realistic Scenario for Lifelong Learning https://arxiv.org/pdf/2103.03216.pdf 

Code: https://github.com/chandar-lab/Lifelong-Hanabi

**Comment by xialeiliu** [comment]
Sure, thanks.
