### ISSUE TITLE
Add ACM MM 2021 Paper

### ISSUE THREAD

**Issue by zhoudw-zdw** [xialeiliu/Awesome-Incremental-Learning#45]
Hi Xialei,

Thanks for your contributions to the incremental learning field. Can I request you to add our recent paper published at ACM MM 2021 in the repo?

Paper: Co-Transport for Class-Incremental Learning https://arxiv.org/pdf/2107.12654.pdf

Code: https://github.com/zhoudw-zdw/MM21-Coil

**Comment by xialeiliu** [comment]
Sure.
