### ISSUE TITLE
what are the differences among incremental learning, continual learning and lifelong learning?

### ISSUE THREAD

**Issue by GodZarathustra** [xialeiliu/Awesome-Incremental-Learning#5]
Hi xialeiliu:
I am new in this area, and this question confused me for a long time:
**What are the differences among the three concepts : Incremental learning, continual learning  and lifelong learning?**
It seems that "continual learning " and ''lifelong learning''  are more conmmonly used in deep learning filed, and incremental learning is more conmmonly used in big data processing. But it also semms that they are addressing the same question in mechine learning: overcome catastrophic forgetting whithout access to old data.
for deep learning, continual learning and lifelong learning was first proposed from the paper<learning without forgetting>(perhaps), but this issue was found in the early neuro networks researches(non-deep), and also widely applied in many areas. 
What's your opinion about this question?

**Comment by luulinh90s** [comment]
Hi @GodZarathustra , I wrote about your question here, hope this helps:
https://github.com/luulinh90s/paper-review-continual-learning/blob/master/distinguish.md

**Comment by moozoohoo** [comment]
In my opinion, they are all the same.

**Comment by arthurdouillard** [comment]
I feel like continual learning = lifelong-learning.

But (class-)incremental learning is about adding new classes at each task, instead of adding new samples of existing classes (online learning). But that's how I see things, may not be standard.

**Comment by sheqi** [comment]
Continual or Lifelong learning is more broadly compared with incremental learning

**Comment by xialeiliu** [comment]
There are subtle differences, better to read some of survey papers to have kind of feelings.

**Comment by yyy24601** [comment]
‘Continual learning’ vs. ‘Lifelong learning’
Often used interchangeably
recently ‘’continual learning" has gained more Popularity 

Especially in recent years, the ‘continual learning’ literature tends to have a more narrow focus:
Traditional ML: all training data available at the same time
Continual learning: 1. Training data arrives incrementally 2. There is non-stationarity
CL- narrow—> how to deal with non-stationarity in training data
LL -broad—> an agent learning throughout its lifetime

Incremental learning include task- domain- and class incremental learning

**Comment by libo-huang** [comment]
> Hi xialeiliu: I am new in this area, and this question confused me for a long time: **What are the differences among the three concepts : Incremental learning, continual learning and lifelong learning?** It seems that "continual learning " and ''lifelong learning'' are more conmmonly used in deep learning filed, and incremental learning is more conmmonly used in big data processing. But it also semms that they are addressing the same question in mechine learning: overcome catastrophic forgetting whithout access to old data. for deep learning, continual learning and lifelong learning was first proposed from the paper(perhaps), but this issue was found in the early neuro networks researches(non-deep), and also widely applied in many areas. What's your opinion about this question?

Good question 🤔.
Looking forward to more professional views 👀.

**Comment by libo-huang** [comment]
> I feel like continual learning = lifelong-learning.
> 
> But (class-)incremental learning is about adding new classes at each task, instead of adding new samples of existing classes (online learning). But that's how I see things, may not be standard.

:+1: Good view. 
Class-incremental learning may relate to adding new classes as the new-coming task. 

In recent years, there has been considerable research on incremental learning, with task, domain, and class incremental learning being widely accepted. Their core differences are illustrated in the diagram below, copied from the paper: Three types of incremental learning[J]. Nature Machine Intelligence, 2022.
![image](https://github.com/xialeiliu/Awesome-Incremental-Learning/assets/24219983/4a6e5210-6dbb-4bee-81b1-aa36a471f224=100x100)

However, I'm still unclear about the core differences between incremental learning, lifelong learning, and continual learning. :sweat_smile:
