### ISSUE TITLE
Missing Papers in AAAI 2021

### ISSUE THREAD

**Issue by dchoi-inha** [xialeiliu/Awesome-Incremental-Learning#54]
Hi,

Thank you for maintaining the list on continual learning.

Would you please add the following paper that is published in AAAI 2021?

Split-and-Bridge: Adaptable Class Incremental Learning within a Single Neural Network, AAAI 2021
https://arxiv.org/abs/2107.01349
https://github.com/bigdata-inha/Split-and-Bridge

Kind Regards,

Don

**Comment by xialeiliu** [comment]
Sure, thanks for your suggestion.
