### ISSUE TITLE
Suggestion to add a survey paper comparing replay for continual learning in the brain and AI

### ISSUE THREAD

**Issue by tyler-hayes** [xialeiliu/Awesome-Incremental-Learning#58]
Hi, I would like to suggest adding our lab's survey paper "Replay in Deep Learning: Current Approaches and Missing Biological Elements"

It was published in Neural Computation (2021). We discuss how replay happens in biological networks and compare it to how replay is implemented for continual learning in artificial networks. We then discuss how the two differ. Thank you in advance!

arXiv: https://arxiv.org/abs/2104.04132
Neural Computation: https://direct.mit.edu/neco/article-abstract/33/11/2908/107071/Replay-in-Deep-Learning-Current-Approaches-and?redirectedFrom=fulltext

**Comment by xialeiliu** [comment]
Hi Tyler, it is a very interesting survey paper, I should have added it before. thanks for your reminder.
