### ISSUE TITLE
WACV 2022 Papers are missing

### ISSUE THREAD

**Issue by pp1016** [xialeiliu/Awesome-Incremental-Learning#59]
There are many good paper related to incremental learning in WACV 2022, we should include them in the website.

**Comment by xialeiliu** [comment]
Thanks for your suggestion. It would be great if you can submit a pull request for it, then I can easily merge it in.

**Comment by pp1016** [comment]
> Thanks for your suggestion. It would be great if you can submit a pull request for it, then I can easily merge it in.

Hi Xialei,
I added two WACV 2022 papers, see pull request, thanks.

**Comment by xialeiliu** [comment]
Many thanks!
