### ISSUE TITLE
Considering the ICML2022 paper

### ISSUE THREAD

**Issue by gydpku** [xialeiliu/Awesome-Incremental-Learning#71]
Hi, could you add some incremental learning papers published in the ICML2022? For example, please consider our paper "Online Continual Learning through Mutual Information Maximization" (https://proceedings.mlr.press/v162/guo22g.html).

**Comment by xialeiliu** [comment]
Yes, of course, I would be very grateful if you can submit a pull request with your paper and more ICML papers.

**Comment by xialeiliu** [comment]
Added, thanks.
