### ISSUE TITLE
Considering the COLING'22 paper

### ISSUE THREAD

**Issue by mqianliu** [xialeiliu/Awesome-Incremental-Learning#84]
Hi Xialei,

Thanks so much for contributing such a great repository! Could you consider adding the paper "Incremental Prompting: Episodic Memory Prompt for Lifelong Event Detection" at COLING'22? It proposed an episodic memory prompting framework for continual event detection.

Paper: https://arxiv.org/abs/2204.07275
Code: https://github.com/VT-NLP/Incremental_Prompting

Thanks for your consideration!

**Comment by xialeiliu** [comment]
Sure, thanks for the suggestion.
