### ISSUE TITLE
Paper recommendation

### ISSUE THREAD

**Issue by salman-h-khan** [xialeiliu/Awesome-Incremental-Learning#9]
Hi Xialei Liu,

You can consider including a recent paper on incremental learning in NeurIPS'19: 

“Random Path Selection for Incremental Learning,” Advances in Neural Information Processing Systems, (NeurIPS), Vancouver, Canada, 2019. 
Arxiv Link: https://arxiv.org/abs/1906.01120

Thanks.

**Comment by xialeiliu** [comment]
yeah, sure!
