### ISSUE TITLE
Are there any incremental learning papers that do not use the old task data?

### ISSUE THREAD

**Issue by incrementallearning** [xialeiliu/Awesome-Incremental-Learning#94]
Are there any incremental learning papers that do not use the old task data?

**Comment by evertonaleixo** [comment]
Yes. They are considered Data-free incremental learning. Some examples are:

* Always Be Dreaming: A New Approach for Data-Free Class-Incremental Learning
* Distilling Causal Effect of Data in Class-Incremental Learning
* Knowledge distillation for incremental learning in semantic segmentation

**Comment by ShiWuxuan** [comment]
- Prototype augmentation and self-supervision for incremental learning
- Self-Sustaining Representation Expansion for Non-Exemplar Class-Incremental Learning
- Prototype Reminiscence and Augmented Asymmetric Knowledge Aggregation for Non-Exemplar Class-Incremental Learning
